### ISSUE TITLE
Dependency is inexplicably removed from package.json by the bump-version commit

### ISSUE THREAD

**Issue by steveswinbank** [phips28/gh-action-bump-version#105]
I have a npm dependency that is OS specific (Windows and Mac use different versions of a BLE library). 

When the bump-version commit is being made on the repo, it's removing the dependency from the package.json file.

I've tried changing the use of the bump-version action to use 'runs-on: windows-latest', but then it fails with 'Error: Container action is only supported on Linux'.

Please help.

![image](https://user-images.githubusercontent.com/64836191/124170748-b5d19a80-da9f-11eb-888d-828b53a0d2d5.png)

**Comment by phips28** [comment]
In the action there is only a bunch of npm scripts executed one by one. Same as you would do in the console.

Have you execute the npm scripts manually to see if that happens as well on your repo?

I never used optional deps. But maybe npm removes them because it cannot be listed twice!? I dont know.

**Comment by the-maazu** [comment]
"Entries in optionalDependencies will override entries of the same name in dependencies, so it's usually best to only put in one place."

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#optionaldependencies.
