### ISSUE TITLE
Cache docker image

### ISSUE THREAD

**Issue by saul-gush** [phips28/gh-action-bump-version#42]
Is there a way to cache the docker image of this action so it doesn't have to build each time? It takes a long time to run and it runs upfront before the rest of the steps.

**Comment by phips28** [comment]
dont know if thats possible.

**Comment by saul-gush** [comment]
Lets cast a net: https://stackoverflow.com/questions/64174918/github-actions-docker-caching :)

**Comment by NoNameProvided** [comment]
Instead of caching, the action can be built as a JS action: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action.

**Comment by TheQueenIsDead** [comment]
I [forked this repo](https://github.com/TheQueenIsDead/gh-action-bump-version), created a [DockerHub repository](https://hub.docker.com/repository/docker/thequeenisdead/gh-action-bump-version), and set up a [demo repo](https://github.com/TheQueenIsDead/action-caching) to attempt to pull a published image instead of building per workflow execution.

Turns out, it's supported, but not very well documented! Investigative work can be found in the StackOverflow question, but for now, please see https://github.com/phips28/gh-action-bump-version/pull/115 for a solution :^)

**Comment by melody-universe** [comment]
> Instead of caching, the action can be built as a JS action: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action.

I've [created a fork](https://github.com/melody-universe/gh-action-bump-version/) that switches this action to a JavaScript action. Unfortunately, [as indicated in this documentation](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github), `node_modules` needs to be present in the repository. I've set up a separate job in the workflow for this repository to download and commit `node_modules` by force, but still keep them in `.gitignore` them while developing.

I would much rather use a bundler like webpack to bundle the assets of this project, but because it depends on [actions-toolkit](https://github.com/JasonEtco/actions-toolkit), which uses dynamic imports, the bundled file [throws an exception](https://github.com/melody-universe/gh-action-bump-version/runs/3270798714?check_suite_focus=true#step:4:16).

**Comment by melody-universe** [comment]
I was really dissatisfied with adding `node_modules` to the repository, so I created a [separate branch in my fork](https://github.com/melody-universe/gh-action-bump-version/tree/bundle-assets) that generates a bundled asset instead.

In order to get this working, I needed to remove [actions-toolkit](https://github.com/JasonEtco/actions-toolkit) and hand-wrote the few pieces of it that this library was actually using. After doing that, it became apparent we might not even need those.

I might create yet another branch that doesn't even use the bundler; if we remove all of our dependencies (right now just [execa](https://github.com/sindresorhus/execa) for spawning a child process and [Signale](https://github.com/klaussinani/signale) for pretty logging), we can just execute `index.js` directly.

**Comment by melody-universe** [comment]
[execa](https://github.com/sindresorhus/execa) was admittedly a little more difficult to peel off, but I created my [last branch (for today)](https://github.com/melody-universe/gh-action-bump-version/tree/remove-dependencies) to remove all runtime dependencies entirely, so that `node_modules` (or a bundled file) isn't even needed at runtime.

Sorry for the PR spam, I wasn't sure which (if any) of these would be preferable... they're sequential but we can squash the PR on whichever one you prefer (also if any).

**Comment by phips28** [comment]
merged. thanks to @melody-universe !
