### ISSUE TITLE
Shouldn't isVersionBump be judged by the last commit? 

### ISSUE THREAD

**Issue by ryan-cha** [phips28/gh-action-bump-version#82]
Hello! 

Following is the log of my Github action workflow. 

```
messages: [
  'ci: fixed invalid action name\nundefined',
  'ci: version bumped into v2.3.21\nundefined',
  'fix: fixed ci script\nundefined',
  "Merge branch 'develop' into staging\nundefined"
]
✔  success   No action necessary!
```

Though I expected the version would have been bumped into `v2.3.22` , it didn't happen. 

So, I opened the source code and I got confused. 

https://github.com/phips28/gh-action-bump-version/blob/e3cde4e376147b58cfa38832db31e73bb214266e/index.js#L24

Shouldn't `isVersionBump` be judged by the last commit, instead of all commits? 

Please correct me if I'm mistaken. Or, I'll make a PR!

**Comment by phips28** [comment]
Its intended to look into all commit messages. 

We could introduce a config flag like `ciCheckInLastMessageOnly` Or any better naming 😉 

if you want to create a PR I can merge it

**Comment by ghm-salvarado** [comment]
Similar issue here, but related to a PR that was squashed and merged:

```
messages: [
  'pull request title\n' +
    '\n' +
    '* squashed commit message\r\n' +
    '\r\n' +
    '* ci: version bump to v0.32.0\r\n' +
    '\r\n' +
    '* squashed commit message\r\n' +
    '\r\n' +
    '* squashed commit message\n' +
    'undefined'
]
✔  success   No action necessary!
```

There's only one string in the `messages` array, but since `ci:` was present in the body of a commit from an upstream merge into this branch, the workflow was skipped. Would it make sense to add a `^` to the regex to ensure only `ci:` in the very beginning of the message triggers a skip?

**Comment by phips28** [comment]
@ghm-salvarado if you want to create a PR I can merge it

**Comment by dallen4** [comment]
Just curious about the status of this issue or if anyone is working on a patch? I implement this version bump in multiple branches (deployment stages) and when merging into production branch it doesn't bump out of the pre-release version because it detects the older bumps. Will work on a flag or something to implement if this isn't being worked on 🙂

**Comment by phips28** [comment]
afaik no one worked on this. So happy to merge your PR.

**Comment by dallen4** [comment]
I took it a step further to allow for a couple settings. See #146.

**Comment by phips28** [comment]
thanks! :)
